version: '3.9'

services:
  postgres:
    image: ankane/pgvector:pg16
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: eventon
      POSTGRES_PASSWORD: eventon
      POSTGRES_DB: eventon
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U eventon']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
